server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://staging-db-host:3306/suyos_auth_db?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: staging_user
    password: ${STAGING_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: never

  kafka:
    bootstrap-servers: staging-kafka:9092
    consumer:
      group-id: user-staging-group

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: https://staging.suyos.com/oauth2/callback/{registrationId}
      resourceserver:
        jwt:
          public-key-location: classpath:keys/public.pem

logging:
  level:
    com.suyos.authservice: INFO
    org.springframework.security: WARN
    org.springframework.web: INFO