apiVersion: v1
kind: ConfigMap
metadata:
  name: authservice-config
data:
  database.url: "jdbc:mysql://mysql:3306/authdb"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: userservice-config
data:
  database.url: "jdbc:mysql://mysql:3306/userdb"
