apiVersion: v1
kind: Secret
metadata:
  name: authservice-secret
type: Opaque
stringData:
  database.username: "root"
  database.password: "root"
---
apiVersion: v1
kind: Secret
metadata:
  name: userservice-secret
type: Opaque
stringData:
  database.username: "root"
  database.password: "root"